version: '3'

services:
  replica1:
    build: .
    ports:
      - "8081:8080"
    environment:
      - ReplicaNumber=1
  replica2:
    build: .
    ports:
      - "8082:8080"
    environment:
      - ReplicaNumber=2
  replica3:
    build: .
    ports:
      - "8083:8080"
    environment:
      - ReplicaNumber=3